apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: userapp-app
  namespace: pfe
  labels:
    team: pfe
spec:
  group: monitoring.coreos.com
  names:
    categories:
    - prometheus-operator
    kind: ServiceMonitor
    listKind: ServiceMonitorList
    plural: servicemonitors
    shortNames:
    - smon
    singular: servicemonitor
  scope: Namespaced
  versions:
  - name: v1
  selector:
    matchLabels:
      app: userapp
  endpoints:
    - port: web
      path: /prometheusMetrics

