apiVersion: v1
kind: Secret
metadata:
  name: userapp-postgresql
  namespace: pfe
  labels:
    app: userapp-postgresql
type: Opaque
data:
  postgresql-password: MzVmZjNlODYxN2FlZjUwOGRkY2M5MGU5OWM0MGRiZGZjNThkY2I4YmVkZTQ5NjExMWNlZDNkNGZjNGRk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapp-postgresql
  namespace: pfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapp-postgresql
  template:
    metadata:
      labels:
        app: userapp-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:14.4
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USER
              value: userapp
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: userapp-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: userapp-postgresql
  namespace: pfe
spec:
  selector:
    app: userapp-postgresql
  ports:
    - port: 5432
